name = "workspace"

[[require]]
name = "PrimeNumberTheoremAnd"
git = "https://github.com/AlexKontorovich/PrimeNumberTheoremAnd"
rev = "57b0698f119db17fae2ee01a4e56651a9b96ea5c"

[[lean_exe]]
name = "blueprint-data"
srcDir = "scripts/blueprint-data"
root = "BlueprintData"
supportInterpreter = true
